package com.sdManager.SDManager.Entity;

public enum TicketStatus {
    CREATED,
    CONFIRMEDANDREQUIRESTECHNICALFEEDBACK,
    SEEVBYTECHINCALTEAMANDFEEDBACKISPROVIDED,
    TICKETCLOSEDAFTERTECHNICALFEEDBACKISREADANDCONFIRMED,
    TECHINCALFEEDBACKREJECTED

}
